name: Build Android

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: |
            /home/runner/work/ionic-ghab/ionic-ghab/android/app/build/outputs/bundle/debug/app-debug.aab
            /home/runner/work/ionic-ghab/ionic-ghab/android/app/build/outputs/bundle/release/app-release.aab

      # ACCESS VIA API
      # REF: https://docs.github.com/en/rest/actions/artifacts#download-an-artifact
      # - name: Upload dev APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-dev
      #     path: /home/runner/work/ionic-ghab/ionic-ghab/android/app/build/outputs/apk/debug/app-debug.apk
      # - name: Upload debug bundle
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-debug
      #     path: /home/runner/work/ionic-ghab/ionic-ghab/android/app/build/outputs/bundle/debug/app-debug.aab
      # - name: Upload release bundle
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release
      #     path: /home/runner/work/ionic-ghab/ionic-ghab/android/app/build/outputs/bundle/release/app-release.aab